import { ref, computed } from 'vue'

export type Lang = 'en' | 'id'

const locale = ref<Lang>('en')

const translations = {
  en: {
    nav: {
      about: 'About',
      experience: 'Experience',
      projects: 'Projects',
      stack: 'Tech Stack',
      contact: 'Contact',
      resume: 'Resume',
      portfolio: 'Portfolio',
      lightMode: 'Switch to light mode',
      darkMode: 'Switch to dark mode',
    },
    hero: {
      eyebrow: 'Portfolio · 2026',
      role: 'Software Developer',
      tagline: 'Crafting fast, elegant and reliable digital products.',
      desc: 'I build modern Android applications (Kotlin, Jetpack Compose, Flutter) and large-scale web information systems (Laravel, React.js, Node.js) for universities and public institutions.',
      viewProjects: 'View Projects',
      portfolio: 'Portfolio',
      downloadCv: 'Download CV',
      scroll: 'Scroll to explore',
      stats: {
        years: 'Years of experience',
        projects: 'Projects delivered',
        platforms: 'Platforms',
        technologies: 'Technologies',
      },
    },
    about: {
      eyebrow: 'About me',
      title: 'Turning complex problems into simple, scalable software.',
      accent: 'scalable software.',
      p1: "I'm a Software Developer based in Padang, Indonesia, specializing in mobile and web development. I build modern Android apps with Kotlin and Jetpack Compose, Flutter-based multi-platform apps, and large-scale web information systems with Laravel, React.js and Node.js.",
      p2: 'I work with MVC and MVVM architectures, REST API integration and databases like MySQL, SQLite and Redis — always applying clean code principles to deliver scalable, efficient digital solutions.',
      p3: 'Currently a Junior Programmer at the IT Directorate of Universitas Andalas, an alumnus of Bangkit Academy 2024, and a national hackathon awardee.',
      currentLabel: 'Currently',
      currentRole: 'Junior Programmer — IT Directorate, Universitas Andalas',
      currentOrg: 'Padang, Indonesia',
      factsLabel: 'Quick facts',
      facts: {
        based: 'Based in',
        email: 'Email',
        education: 'Education',
        focus: 'Focus',
        status: 'Status',
      },
      educationValue: 'S1 Information Systems · IPK 3.76',
      statusValue: 'Open to collaborations',
      focusValue: 'Mobile · Web · API design',
      strengths: 'Core strengths',
      strengthsList: [
        'Android (Kotlin & Compose)',
        'Flutter multi-platform',
        'Laravel & React.js',
        'REST API design',
        'Databases & caching',
        'Clean architecture',
      ],
    },
    experience: {
      eyebrow: 'Journey',
      title: 'Experience & milestones',
      desc: 'A look at where I have worked, built and learned along the way.',
      present: 'Present',
      internship: 'Internship',
      organization: 'Organization',
      education: 'Education',
    },
    projects: {
      eyebrow: 'Selected work',
      title: 'Featured projects',
      accent: 'projects',
      desc: 'Web information systems and Android applications I have designed, built and shipped.',
      features: 'Key features',
      code: 'Source code',
      demo: 'Live demo',
      more: 'More projects on GitHub',
      stream: {
        gitLog: 'git log --graph --oneline',
        main: 'main',
        head: 'HEAD',
        web: 'web',
        mobile: 'mobile',
        details: 'Inspect',
        hint: 'Click a commit to inspect architecture & schema',
      },
      drawer: {
        architecture: 'System architecture',
        schema: 'Database schema',
        close: 'Close details',
      },
    },
    stack: {
      eyebrow: 'Toolbox',
      title: 'My tech stack',
      desc: 'The technologies I use to design, build and ship products end to end.',
    },
    achievements: {
      eyebrow: 'Milestones',
      title: 'Achievements & recognition',
      desc: 'Certifications, hackathons and leadership roles along the journey.',
      certification: 'Certification',
      award: 'Award',
      hackathon: 'Hackathon',
    },
    contact: {
      eyebrow: 'Contact',
      title: "Let's build something great together.",
      accent: 'great',
      desc: 'Have a project in mind, an opportunity, or just want to say hi? My inbox is always open.',
      emailCta: 'Send me an email',
      reply: 'I usually reply within 24 hours.',
    },
    footer: {
      tagline: 'Software Developer crafting fast, elegant digital products.',
      rights: 'All rights reserved.',
      built: 'Designed & built with Vue 3, Tailwind CSS and motion-v.',
      backToTop: 'Back to top',
    },
  },
  id: {
    nav: {
      about: 'Tentang',
      experience: 'Pengalaman',
      projects: 'Proyek',
      stack: 'Teknologi',
      contact: 'Kontak',
      resume: 'CV',
      portfolio: 'Portofolio',
      lightMode: 'Ganti ke mode terang',
      darkMode: 'Ganti ke mode gelap',
    },
    hero: {
      eyebrow: 'Portofolio · 2026',
      badge: 'Terbuka untuk peluang baru',
      role: 'Software Developer',
      tagline: 'Membuat produk digital yang cepat, elegan, dan andal.',
      desc: 'Saya membangun aplikasi Android modern (Kotlin, Jetpack Compose, Flutter) dan sistem informasi web berskala besar (Laravel, React.js, Node.js) untuk universitas dan instansi publik.',
      viewProjects: 'Lihat Proyek',
      portfolio: 'Portofolio',
      downloadCv: 'Unduh CV',
      scroll: 'Gulir untuk menjelajah',
      stats: {
        years: 'Tahun pengalaman',
        projects: 'Proyek selesai',
        platforms: 'Platform',
        technologies: 'Teknologi',
      },
    },
    about: {
      eyebrow: 'Tentang saya',
      title: 'Mengubah masalah kompleks menjadi perangkat lunak yang sederhana dan skalabel.',
      accent: 'skalabel.',
      p1: "Saya adalah Software Developer berbasis di Padang, Indonesia, yang berfokus pada pengembangan mobile dan web. Saya membangun aplikasi Android modern dengan Kotlin dan Jetpack Compose, aplikasi multi-platform dengan Flutter, serta sistem informasi web berskala besar dengan Laravel, React.js dan Node.js.",
      p2: 'Saya terbiasa menggunakan arsitektur MVC dan MVVM, integrasi REST API, serta manajemen database seperti MySQL, SQLite dan Redis — selalu menerapkan prinsip clean code untuk menghasilkan solusi digital yang skalabel dan efisien.',
      p3: 'Saat ini menjadi Junior Programmer di Direktorat Teknologi Informasi Universitas Andalas, alumni Bangkit Academy 2024, dan peraih penghargaan hackathon nasional.',
      currentLabel: 'Saat ini',
      currentRole: 'Junior Programmer — Direktorat Teknologi Informasi, Universitas Andalas',
      currentOrg: 'Padang, Indonesia',
      factsLabel: 'Fakta singkat',
      facts: {
        based: 'Berbasis di',
        email: 'Email',
        education: 'Pendidikan',
        focus: 'Fokus',
        status: 'Status',
      },
      educationValue: 'S1 Sistem Informasi · IPK 3.76',
      statusValue: 'Terbuka untuk kolaborasi',
      focusValue: 'Mobile · Web · Desain API',
      strengths: 'Keahlian utama',
      strengthsList: [
        'Android (Kotlin & Compose)',
        'Flutter multi-platform',
        'Laravel & React.js',
        'Desain REST API',
        'Database & caching',
        'Clean architecture',
      ],
    },
    experience: {
      eyebrow: 'Perjalanan',
      title: 'Pengalaman & pencapaian',
      desc: 'Sepanjang perjalanan saya bekerja, membangun, dan belajar.',
      present: 'Sekarang',
      internship: 'Magang',
      organization: 'Organisasi',
      education: 'Pendidikan',
    },
    projects: {
      eyebrow: 'Karya pilihan',
      title: 'Proyek unggulan',
      accent: 'unggulan',
      desc: 'Sistem informasi web dan aplikasi Android yang saya rancang, bangun, dan luncurkan.',
      features: 'Fitur utama',
      code: 'Kode sumber',
      demo: 'Demo langsung',
      more: 'Proyek lainnya di GitHub',
      stream: {
        gitLog: 'git log --graph --oneline',
        main: 'main',
        head: 'HEAD',
        web: 'web',
        mobile: 'mobile',
        details: 'Inspect',
        hint: 'Klik commit untuk melihat arsitektur & skema',
      },
      drawer: {
        architecture: 'Arsitektur sistem',
        schema: 'Skema database',
        close: 'Tutup detail',
      },
    },
    stack: {
      eyebrow: 'Peralatan',
      title: 'Tech stack saya',
      desc: 'Teknologi yang saya gunakan untuk merancang, membangun, dan meluncurkan produk secara menyeluruh.',
    },
    achievements: {
      eyebrow: 'Pencapaian',
      title: 'Prestasi & pengakuan',
      desc: 'Sertifikasi, hackathon, dan peran kepemimpinan di sepanjang perjalanan.',
      certification: 'Sertifikasi',
      award: 'Penghargaan',
      hackathon: 'Hackathon',
    },
    contact: {
      eyebrow: 'Kontak',
      title: 'Mari membangun sesuatu yang hebat bersama.',
      accent: 'hebat',
      desc: 'Punya proyek, peluang, atau sekadar ingin menyapa? Inbox saya selalu terbuka.',
      emailCta: 'Kirim email',
      reply: 'Saya biasanya membalas dalam 24 jam.',
    },
    footer: {
      tagline: 'Software Developer yang membuat produk digital cepat dan elegan.',
      rights: 'Hak cipta dilindungi.',
      built: 'Dirancang & dibangun dengan Vue 3, Tailwind CSS, dan motion-v.',
      backToTop: 'Kembali ke atas',
    },
  },
}

export function useLang() {
  const toggleLang = () => {
    locale.value = locale.value === 'en' ? 'id' : 'en'
  }

  const t = computed(() => translations[locale.value])

  return { locale, toggleLang, t }
}
